server:
  port: 8080

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
      
app:
  config:
    keycloak:
      url: http://localhost:8180/auth
      realm: master

spring:
     
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/token
            authorization-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/auth
            user-name-attribute: preferred_username
            user-info-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs
            user-info-authentication-method: header
        registration:
          internet-banking-core-client:
            provider: keycloak
            client-id: MyClientApp
            client-secret: 2Wwb8PyuZD7ak2mPsm3lCBJ0B19JN4sZ
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
            scope: openid
      resourceserver:
        jwt:
          jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs      

  application:
    name: apigateway
  cloud:
    # A client sends a request to Spring Cloud Gateway. If the request matches a route through its predicates, the Gateway HandlerMapping will send the request to the Gateway WebHandler, which in turn will run the request through a chain of filters.
    gateway:
    
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET
            - POST 
      # For automatic route discovery through Eureka
      discovery.locator:
        enabled: false
        lowerCaseServiceId: true
      # Route. It’s identified by a unique ID, a collection of predicates deciding whether to follow the route, a URI for forwarding the request if the predicates allow, and a collection of filters applied either before or after forwarding the request downstream.
      routes:
        - id: usermsmodule
          uri: lb://USERMS
          predicates:
            - Path=/userms/**
          filters:
            - RewritePath=/userms/(?<path>.*), /$\{path}
        - id: patientmsmodule
          uri: lb://PATIENTMS
          predicates:
            - Path=/patientms/**
          filters:
            - RewritePath=/patientms/(?<path>.*), /$\{path}
        - id: appointmentmsmodule
          uri: lb://APPOINTMENTMS
          predicates:
            - Path=/appointmentms/**
          filters:
            - RewritePath=/appointmentms/(?<path>.*), /$\{path}
        - id: vitalsignmsmodule
          uri: lb://VITALSIGNMS
          predicates:
            - Path=/vitalsignms/**
          filters:
            - RewritePath=/vitalsignms/(?<path>.*), /$\{path}
        - id: authmsmodule
          uri: lb://AUTHMS
          predicates:
            - Path=/authms/**
          filters:
            - RewritePath=/authms/(?<path>.*), /$\{path}
        - id: inboxmsmodule
          uri: lb://INBOXMS
          predicates:
            - Path=/inboxms/**
          filters:
            - RewritePath=/inboxms/(?<path>.*), /$\{path}
        - id: patientvisitmsmodule
          uri: lb://PATIENTVISITMS
          predicates:
            - Path=/patientvisitms/**
          filters:
            - RewritePath=/patientvisitms/(?<path>.*), /$\{path}
        - id: patientvisiturl
          uri: http://localhost:8087
          predicates:
            - Path=/patientvisiturl/**
          filters:
            - RewritePath=/patientvisiturl/(?<path>.*), /$\{path}
        - id: authurl
          uri: http://localhost:8083
          predicates:
            - Path=/authurl/**
          filters:
            - RewritePath=/authurl/(?<path>.*), /$\{path}
        - id: inboxurl
          uri: http://localhost:8086
          predicates:
            - Path=/inboxurl/**
          filters:
            - RewritePath=/inboxurl/(?<path>.*), /$\{path}
        - id: userurl
          uri: http://localhost:8081
          predicates:
            - Path=/userurl/**
          filters:
            - RewritePath=/userurl/(?<path>.*), /$\{path}
        - id: vitalsignurl
          uri: http://localhost:8082
          predicates:
            - Path=/vitalsignurl/**
          filters:
            - RewritePath=/vitalsignurl/(?<path>.*), /$\{path}  
        - id: patienturl
          uri: http://localhost:8084
          predicates:
            - Path=/patienturl/**
          filters:
            - RewritePath=/patienturl/(?<path>.*), /$\{path}      
        - id: appointmenturl
          uri: http://localhost:8085
          predicates:
            - Path=/appointmenturl/**
          filters:
            - RewritePath=/appointmenturl/(?<path>.*), /$\{path}
            
            

management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    com.netflix: WARN
    org.springframework.web: DEBUG
    com.edu: DEBUG
    

    